### ISSUE TITLE
How to set the timer

### ISSUE THREAD

**Issue by reserect** [CrazyHobo420/hobo_weedfarm#1]
Hi just wondering where abouts you set the timer in the configs.

**Comment by CrazyHobo420** [comment]
It says how to do so in the README.

**Comment by CrazyHobo420** [comment]
![image](https://user-images.githubusercontent.com/13574181/193478905-2f7b5e67-9af1-4539-95cd-2103c0800788.png)

**Comment by reserect** [comment]
Sorry missed that lol
