### ISSUE TITLE
Script Loads but has error

### ISSUE THREAD

**Issue by maddysinko** [CrazyHobo420/hobo_weedfarm#2]
Script Loads With but when going to use weed seed it doesnt come up with optiong to plant items are in sql DB  aswell shows invisible plant and cant put it down. doesnt come up with a mouse option or button to place weed prop.
error screen shot
![Screenshot_16](https://github.com/CrazyHobo420/hobo_weedfarm/assets/71648455/e19db440-a4f2-4d11-983a-7e23b6ae714d)

![Screenshot_15](https://github.com/CrazyHobo420/hobo_weedfarm/assets/71648455/eaf8f1da-8c0e-404f-bb5a-fb1219c9cafe)

**Comment by CrazyHobo420** [comment]
I don't offer support for this. And I don't update it anymore.
